-- =============================================
-- INSERT GARKI WARD POLLING UNITS
-- =============================================

-- Garki Ward (04) Polling Units
INSERT INTO polling_units (ward_id, unit_number, unit_name, location)
SELECT w.id, p.unit_number, p.unit_name, p.location
FROM wards w
CROSS JOIN (
    VALUES 
        ('006', 'Former Pri. Sch / Musa Ahmad (Garki Village)', 'Garki'),
        ('007', 'CBN Quarters Garki', 'Garki'),
        ('008', 'CBN Quarters, Near Police Head Quarters', 'Garki'),
        ('009', 'Garki II, Rachael Eye Clinic Area 11', 'Garki'),
        ('010', 'Asokoro I, New Capital Primary School', 'Asokoro'),
        ('011', 'Asokoro I, New Capital Primary School II', 'Asokoro'),
        ('012', 'Asokoro II, Near ECOWAS Secretariat', 'Asokoro'),
        ('013', 'Asokoro II, Near ECOWAS Secretariat II', 'Asokoro'),
        ('014', 'Kpaduma Village', 'Kpaduma'),
        ('015', 'Ungunwa Fulani Village / Guzape I', 'Guzape'),
        ('016', 'Kobin Madaki Village', 'Garki'),
        ('017', 'Apo Legislative Quarters', 'Apo'),
        ('018', 'Apo Legislative Post to Mechanic Village', 'Apo'),
        ('019', 'Akpa Jenya Village, Apo', 'Apo'),
        ('020', 'Apo Village, Near Danko Gi Filing Station', 'Apo'),
        ('021', 'Durumi I, Durumi Primary School', 'Durumi'),
        ('022', 'Durumi II, Durumi Primary School', 'Durumi'),
        ('023', 'Dutse Baba Pri School', 'Dutse'),
        ('024', 'Infront of Garki Service, Garki Village', 'Garki'),
        ('025', 'Unguwan Fulani / Zamal Garki Village', 'Garki'),
        ('026', 'Unguwan Hausana Garki Village', 'Garki'),
        ('027', 'Opposite Sopey Embs Palace', 'Garki'),
        ('028', 'Beside Police Barracks Lagos Street', 'Garki'),
        ('029', 'Inside Police Barracks By The Gate', 'Garki'),
        ('030', 'Pantaker Garki Village', 'Garki'),
        ('031', 'Garki Village', 'Garki'),
        ('032', 'Garki Village II', 'Garki'),
        ('033', 'Ungunwan Gan Care Garki Village', 'Garki'),
        ('034', 'Ungunwan Waziri Garki Village', 'Garki'),
        ('035', 'Enugu Street Nsukka Street Junction', 'Garki'),
        ('036', 'Enugu Street by Iyabadan', 'Garki'),
        ('037', 'Beside Lewa Church Near Market Street Garki', 'Garki'),
        ('038', 'Infront of Garki Hotel', 'Garki'),
        ('039', 'Infront of Wine Shop, Lagos Street', 'Garki'),
        ('040', 'Lagos Street by Drumstick', 'Garki'),
        ('041', 'Oka Akoko Street by Access Bank', 'Garki'),
        ('042', 'Oka Akoko Street by Access Bank II', 'Garki'),
        ('044', 'Opp. Diamond Bank Ladoke Akintola', 'Garki'),
        ('045', 'Schicken Republic Garki Village', 'Garki'),
        ('046', 'Tantalizer Garki Village', 'Garki'),
        ('047', 'Keffi Street Junction', 'Garki'),
        ('048', 'Ubiaja Crescent by FCMB Garki', 'Garki'),
        ('049', 'Nuruw Garki by Jamnab Plaza', 'Garki'),
        ('050', 'Nepa Office Garki', 'Garki'),
        ('051', 'Karatnogo Street by Transformer', 'Garki'),
        ('052', 'Ilwon Brass by Ukpo close Garki', 'Garki'),
        ('054', 'Oke Abhe Close Garki II T-Junction', 'Garki'),
        ('055', 'CBN QTRS by Oando Filling Station', 'Garki'),
        ('056', 'Total Filling Station opp. Police H/Q', 'Garki'),
        ('057', 'Gimbiya Street by H-medix Area 11 Garki', 'Garki'),
        ('058', 'Area 11 Police Cantonment Garki Abuja', 'Garki'),
        ('059', 'Unity House Muhammed Rochas Foundation Garki', 'Garki'),
        ('060', 'Garki II, NNPC Main gate area 11 by Gimbiya', 'Garki'),
        ('061', 'Sahad Stores by Bolton White Hotel', 'Garki'),
        ('062', 'Community School Asokoro', 'Asokoro'),
        ('063', 'Ajayi Crowther Street', 'Asokoro'),
        ('064', 'A''arano Filling Station', 'Asokoro'),
        ('066', 'T.Y Danjuma by Kebbi State Lodge', 'Asokoro'),
        ('067', 'Justice M. Bello Street Asokoro By Delta State Liaison Office', 'Asokoro'),
        ('068', 'Mediterranean Recreational Club park Asokoro', 'Asokoro'),
        ('069', 'Sunrise Junction', 'Asokoro'),
        ('070', 'Nelson Mandela Street', 'Asokoro'),
        ('071', 'Kwambo Nkurumo Cr. by Togo Embassy', 'Asokoro'),
        ('072', 'Haile Selassie Street By Transformer', 'Asokoro'),
        ('073', 'Thomas Sankara Street ECOWAS', 'Asokoro'),
        ('074', 'In front of Federal Housing Authority', 'Asokoro'),
        ('075', 'Oliver Tambo Street by Kokoro Hospital', 'Asokoro'),
        ('076', 'Gamel Abdel Nasser Street Asokoro by Capital Club', 'Asokoro'),
        ('077', 'Julius Nyerere Street by UBA', 'Asokoro'),
        ('078', 'By Dollar Pharmacy Julius Nyerere Crescent', 'Asokoro'),
        ('079', 'Open field outside Junior Secondary School Kpaduma I', 'Kpaduma'),
        ('080', 'Football Field Kpaduma I', 'Kpaduma'),
        ('081', 'Open field by ECINA Church Kpaduma II', 'Kpaduma'),
        ('082', 'Open Space in front of district Head office', 'Garki'),
        ('085', 'Kpebi Sarki Settlement', 'Garki'),
        ('086', 'Open field Opp INEC Comm. QTRS', 'Garki'),
        ('087', 'NNPC Filling Station', 'Garki'),
        ('088', 'Opposite Alhabibiya Mosque', 'Garki'),
        ('089', 'Football Field Kpebi Madaki', 'Garki'),
        ('090', 'Primary Health care Kpebi Madaki', 'Garki'),
        ('091', 'AEoc office Kpebi', 'Garki'),
        ('092', 'Densi Osadabay Crescent Apo Legies Quarters', 'Apo'),
        ('093', 'In Front Of Airforce quarters A Shalleng close', 'Apo'),
        ('094', 'Federal Government Boys College Apo', 'Apo'),
        ('095', 'In front of Sharia Court of Appeal Apo', 'Apo'),
        ('096', 'National Library Gudu', 'Gudu'),
        ('101', 'Anglican Church Of Transformation Gaduwa', 'Gaduwa'),
        ('102', 'Oando Filling Station Gaduwa', 'Gaduwa'),
        ('105', 'Prince And Princess corner Shop', 'Gaduwa'),
        ('106', 'Prince And Princess 2nd Gate', 'Gaduwa'),
        ('107', 'Foot Ball field', 'Gaduwa'),
        ('108', 'Kaura Market Exit Gate', 'Gaduwa'),
        ('109', 'Broadway Mall Beside Kaura Market', 'Gaduwa'),
        ('110', 'Apo Legies Quarter Zone D 1st Gate', 'Apo'),
        ('112', 'Halibiz Shopping Mall', 'Apo'),
        ('113', 'Eternal Filling Station', 'Apo'),
        ('114', 'AEDC Apo Regional Office', 'Apo'),
        ('115', 'Nuruw Jibril Street by Transformer Dutse', 'Dutse'),
        ('116', 'Apo Extension (PIGBA)', 'Apo'),
        ('117', 'Acmzy Unique School', 'Apo'),
        ('118', 'Bony West Hotel by Transformer', 'Apo'),
        ('121', 'Ayum Small Filling station', 'Apo'),
        ('122', 'Copa Cabaova Estate', 'Apo'),
        ('124', 'High Court Junction by in Grosa Academy Apo Resettlement', 'Apo'),
        ('127', 'AEDC Office Zone D', 'Apo'),
        ('128', 'Apo town hall', 'Apo'),
        ('129', 'Primary Health Care Zone 13', 'Apo'),
        ('130', 'Purple Stone Plaza', 'Apo'),
        ('131', 'Apo Stadium', 'Apo'),
        ('132', 'New Garki Model Sec School Apo Village', 'Apo'),
        ('133', 'Ambi Mbikan Str Transform Zon Extension', 'Apo'),
        ('135', 'Divine Victorious Leaders Academy', 'Apo'),
        ('136', 'Apo Sparklite Mall Junction', 'Apo'),
        ('137', 'National Automobile Design and Development Council', 'Apo'),
        ('138', 'Isah Muhammed Street Durumi I By Transformer', 'Durumi'),
        ('140', 'Dubai Market Games Village', 'Games Village'),
        ('141', 'Wonderland Estate', 'Games Village'),
        ('142', 'Excel Specialist Hospital and Eternity', 'Games Village'),
        ('143', 'Olympia Estate', 'Games Village'),
        ('144', 'Douglas Crescent off Games Village', 'Games Village'),
        ('145', 'Open Field carwash By Games Village', 'Games Village'),
        ('146', 'Abdulkarim Adisa Estate Durumi II', 'Durumi'),
        ('147', 'Princewill Str Junction', 'Durumi'),
        ('148', 'Covenant Foundation School', 'Durumi'),
        ('149', 'Junior Secondary School', 'Durumi'),
        ('150', 'Princewill Ihedigbo street By Transformer', 'Durumi'),
        ('151', 'IEC Crescent By Transformer', 'Durumi'),
        ('152', 'Primary Health Care Durumi II', 'Durumi'),
        ('155', 'Brookville Hotel Beside Ebano', 'Durumi'),
        ('156', 'Dama Gaza Settlement', 'Durumi'),
        ('157', 'Primary Health care Damadaza', 'Durumi'),
        ('158', 'Dakno Village', 'Dutse'),
        ('159', 'Nomadic Primary And Secondary School Dutse', 'Dutse'),
        ('160', 'Abuja Investment Estate', 'Dutse'),
        ('161', 'Number-one Luxury Estate', 'Dutse'),
        ('162', 'And Hammer Estate', 'Dutse'),
        ('164', 'Efab Estate Apo', 'Apo'),
        ('165', 'Ccnmage Amina Court Estate', 'Apo'),
        ('168', 'Choose Estate CBN Quarters', 'Garki'),
        ('171', 'Chahuyi Village', 'Garki')
) AS p(unit_number, unit_name, location)
WHERE w.ward_number = '04'
ON CONFLICT (ward_id, unit_number) DO NOTHING;

SELECT 'Garki Ward polling units inserted: ' || COUNT(*) FROM polling_units WHERE ward_id = (SELECT id FROM wards WHERE ward_number = '04');
